<a href="https://colab.research.google.com/github/MD-TANVIR-ALAM/JovianP/blob/main/jovian_ex_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

# Example 1: Simple SVD
matrix1 = torch.tensor([[3., 2., 2.], [2., 3., -2.]])
U1, S1, V1 = torch.svd(matrix1)

# Example 2: SVD with a larger matrix
matrix2 = torch.randn(4, 5)
U2, S2, V2 = torch.svd(matrix2)

# Errorable example: SVD on a non-2D tensor
matrix3 = torch.tensor([1., 2.])
try:
    U3, S3, V3 = torch.svd(matrix3)
except Exception as e:
    error_message = str(e)

print('Example 1 - U:\n', U1)
print('Example 1 - S:\n', S1)
print('Example 1 - V:\n', V1)
print('\nExample 2 - U:\n', U2)
print('Example 2 - S:\n', S2)
print('Example 2 - V:\n', V2)
print('\nErrorable example error message:\n', error_message)

Example 1 - U:
 tensor([[ 0.7071, -0.7071],
        [ 0.7071,  0.7071]])
Example 1 - S:
 tensor([5.0000, 3.0000])
Example 1 - V:
 tensor([[ 7.0711e-01, -2.3570e-01],
        [ 7.0711e-01,  2.3570e-01],
        [ 4.2130e-08, -9.4281e-01]])

Example 2 - U:
 tensor([[ 0.0572,  0.4842, -0.8729,  0.0188],
        [-0.6844,  0.4589,  0.1983, -0.5307],
        [ 0.2398,  0.7268,  0.4292,  0.4796],
        [-0.6861, -0.1633, -0.1206,  0.6986]])
Example 2 - S:
 tensor([3.6507, 2.0463, 1.2610, 0.5091])
Example 2 - V:
 tensor([[-0.1218, -0.5522, -0.0575,  0.0569],
        [ 0.3676, -0.4582, -0.4942,  0.5514],
        [ 0.8629,  0.3368, -0.0275, -0.1068],
        [ 0.3235, -0.5677,  0.6591, -0.2565],
        [-0.0263,  0.2224,  0.5633,  0.7845]])

Errorable example error message:
 linalg.svd: input should have at least 2 dimensions, but has 1 dimensions instead
