<a href="https://colab.research.google.com/github/MD-TANVIR-ALAM/JovianP/blob/main/jovian_ex_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

# Example 1: Simple SVD
matrix1 = torch.tensor([[3., 2., 2.], [2., 3., -2.]])
U1, S1, V1 = torch.svd(matrix1)

# Example 2: SVD with a larger matrix
matrix2 = torch.randn(4, 5)
U2, S2, V2 = torch.svd(matrix2)

# Errorable example: SVD on a non-2D tensor
matrix3 = torch.tensor([1., 2.])
try:
    U3, S3, V3 = torch.svd(matrix3)
except Exception as e:
    error_message = str(e)

print('Example 1 - U:\n', U1)
print('Example 1 - S:\n', S1)
print('Example 1 - V:\n', V1)
print('\nExample 2 - U:\n', U2)
print('Example 2 - S:\n', S2)
print('Example 2 - V:\n', V2)
print('\nErrorable example error message:\n', error_message)

Example 1 - U:
 tensor([[ 0.7071, -0.7071],
        [ 0.7071,  0.7071]])
Example 1 - S:
 tensor([5.0000, 3.0000])
Example 1 - V:
 tensor([[ 7.0711e-01, -2.3570e-01],
        [ 7.0711e-01,  2.3570e-01],
        [ 4.2130e-08, -9.4281e-01]])

Example 2 - U:
 tensor([[ 0.4944,  0.8315, -0.0204,  0.2525],
        [-0.5111,  0.3628,  0.7680, -0.1317],
        [ 0.6002, -0.4157,  0.6378,  0.2452],
        [-0.3661, -0.0650, -0.0541,  0.9267]])
Example 2 - S:
 tensor([2.5130, 2.3047, 1.6160, 0.8997])
Example 2 - V:
 tensor([[-0.3956, -0.5908,  0.5109,  0.2678],
        [ 0.3525, -0.0606,  0.6327,  0.1769],
        [-0.8107,  0.0331, -0.0495, -0.2199],
        [ 0.0721,  0.0745,  0.4320, -0.8706],
        [ 0.2385, -0.8004, -0.3867, -0.3012]])

Errorable example error message:
 linalg.svd: input should have at least 2 dimensions, but has 1 dimensions instead


In [3]:
# Function 4: torch.linalg.eig
# Description: Computes the eigenvalues and eigenvectors of a real square matrix.

# Example 1
N = torch.tensor([[2.0, 0.0], [0.0, 3.0]], dtype=torch.float32)
result7 = torch.linalg.eig(N)

# Example 2
O = torch.tensor([[4.0, -2.0], [1.0, 1.0]], dtype=torch.float32)
result8 = torch.linalg.eig(O)

# Corrected Errorable Example
# This tensor Q is not a 2D square matrix, it's 1D
Q = torch.tensor([2.0, 0.0, 3.0], dtype=torch.float32)
try:
    error_result4 = torch.linalg.eig(Q)
except Exception as e:
    error_message4 = str(e)

print('Example 1 Result:\n', result7)
print('Example 2 Result:\n', result8)
print('Errorable Example Error:\n', error_message4)

Example 1 Result:
 torch.return_types.linalg_eig(
eigenvalues=tensor([2.+0.j, 3.+0.j]),
eigenvectors=tensor([[1.+0.j, 0.+0.j],
        [0.+0.j, 1.+0.j]]))
Example 2 Result:
 torch.return_types.linalg_eig(
eigenvalues=tensor([3.+0.j, 2.+0.j]),
eigenvectors=tensor([[0.8944+0.j, 0.7071+0.j],
        [0.4472+0.j, 0.7071+0.j]]))
Errorable Example Error:
 linalg.eig: The input tensor A must have at least 2 dimensions.


In [4]:
# Function 3: torch.det
# Description: Computes the determinant of a matrix.

# Example 1
J = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
result5 = torch.det(J)

# Example 2
K = torch.tensor([[7.0, 2.0], [3.0, 6.0]])
result6 = torch.det(K)

# Corrected Errorable Example
# This tensor M is not a 2D square matrix, it's 1D
M = torch.tensor([1.0, 2.0, 3.0])
try:
    error_result3 = torch.det(M)
except Exception as e:
    error_message3 = str(e)

print('Example 1 Result:\n', result5)
print('Example 2 Result:\n', result6)
print('Errorable Example Error:\n', error_message3)

Example 1 Result:
 tensor(-2.)
Example 2 Result:
 tensor(36.)
Errorable Example Error:
 linalg.det: The input tensor A must have at least 2 dimensions.


In [5]:
import torch
from tqdm import tqdm
import time

# Function 1: torch.matmul
# Description: Performs matrix multiplication.

# Example 1
A = torch.tensor([[1, 2], [3, 4]])
B = torch.tensor([[5, 6], [7, 8]])
result1 = torch.matmul(A, B)

# Example 2
C = torch.tensor([[1, 2], [3, 4], [5, 6]])
D = torch.tensor([[7, 8], [9, 10]])
result2 = torch.matmul(C, D)

# Errorable Example
E = torch.tensor([[1, 2], [3, 4]])
F = torch.tensor([5, 6, 7])
try:
    error_result = torch.matmul(E, F)
except Exception as e:
    error_message = str(e)

print('Example 1 Result:\n', result1)
print('Example 2 Result:\n', result2)
print('Errorable Example Error:\n', error_message)

Example 1 Result:
 tensor([[19, 22],
        [43, 50]])
Example 2 Result:
 tensor([[ 25,  28],
        [ 57,  64],
        [ 89, 100]])
Errorable Example Error:
 size mismatch, got input (2), mat (2x2), vec (3)


In [6]:
# Function 2: torch.inverse
# Description: Computes the inverse of a square matrix.

# Example 1
G = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
result3 = torch.inverse(G)

# Example 2
H = torch.tensor([[7.0, 2.0], [3.0, 6.0]])
result4 = torch.inverse(H)

# Errorable Example
I = torch.tensor([[1.0, 2.0], [2.0, 4.0]]) # This is a singular matrix
try:
    error_result2 = torch.inverse(I)
except Exception as e:
    error_message2 = str(e)

print('Example 1 Result:\n', result3)
print('Example 2 Result:\n', result4)
print('Errorable Example Error:\n', error_message2)

Example 1 Result:
 tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]])
Example 2 Result:
 tensor([[ 0.1667, -0.0556],
        [-0.0833,  0.1944]])
Errorable Example Error:
 linalg.inv: The diagonal element 2 is zero, the inversion could not be completed because the input matrix is singular.


In [7]:
# Function 4: torch.linalg.eig
# Description: Computes the eigenvalues and eigenvectors of a real square matrix.

# Example 1
N = torch.tensor([[2.0, 0.0], [0.0, 3.0]], dtype=torch.float32)
result7 = torch.linalg.eig(N)

# Example 2
O = torch.tensor([[4.0, -2.0], [1.0, 1.0]], dtype=torch.float32)
result8 = torch.linalg.eig(O)

# Corrected Errorable Example
# This tensor Q is not a 2D square matrix, it's 1D
Q = torch.tensor([2.0, 0.0, 3.0], dtype=torch.float32)
try:
    error_result4 = torch.linalg.eig(Q)
except Exception as e:
    error_message4 = str(e)

print('Example 1 Result:\n', result7)
print('Example 2 Result:\n', result8)
print('Errorable Example Error:\n', error_message4)

Example 1 Result:
 torch.return_types.linalg_eig(
eigenvalues=tensor([2.+0.j, 3.+0.j]),
eigenvectors=tensor([[1.+0.j, 0.+0.j],
        [0.+0.j, 1.+0.j]]))
Example 2 Result:
 torch.return_types.linalg_eig(
eigenvalues=tensor([3.+0.j, 2.+0.j]),
eigenvectors=tensor([[0.8944+0.j, 0.7071+0.j],
        [0.4472+0.j, 0.7071+0.j]]))
Errorable Example Error:
 linalg.eig: The input tensor A must have at least 2 dimensions.
